#********************************************************************************PATH********************************************************************************
# Output
output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_anxiety_corpus'

# Data
pretrain_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/corpus/ProcessedRedditRawData/Anxiety_submissions.csv'

# Bert Config
bert_config: 'C:/Winston/MentalHealthResearch/mentalhealth/configs/model/bert_base.json'

#********************************************************************************TRAIN********************************************************************************
# Device
device: 'cuda:0'

# Param
batch_size: 8
#max_epoch: 100
max_epoch: 2
early_stop: 10

# Optimizer
weight_decay: 0.02
init_lr: 0.0005
min_lr: 0.000001
warmup_lr: 0.000001
lr_decay_rate: 0.9
warmup_steps: 3000

# Prompt
prompt: ''

#********************************************************************************MODEL********************************************************************************
# Model Name
model_name: 'bert-base-uncased'