#********************************************************************************PATH********************************************************************************
# Output
output_dir: '../store_model/bert_corpus_sent'

# Data
pretrain_path: '../data/corpus/ProcessedRedditRawData'

# Bert Config
bert_config: '../configs/model/bert_base.json'

# Checkpoint
train_checkpoint: ''

#********************************************************************************TRAIN********************************************************************************
# Num GPU
num_gpu: 8

# Distributed training
package: 'nccl'

# Device
device: 'cuda'

# Param
batch_size: 64
max_epoch: 100
early_stop: 5

# Optimizer
#init_lr: 0.00005
#min_lr: 0.000001
#warmup_lr: 0.000001
init_lr: 0.0001
min_lr: 0.00001
warmup_lr: 0.00001
weight_decay: 0.02
lr_decay_rate: 0.9
warmup_steps: 3000

#********************************************************************************MODEL********************************************************************************
# Model Name
bert_model: 'bert-base-uncased'