#********************************************************************************PATH********************************************************************************
# Output
output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_anxiety_corpus'

# Data
pretrain_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/corpus/ProcessedRedditRawData/Anxiety_submissions.csv'

# Bert Config
bert_config: 'C:/Winston/MentalHealthResearch/mentalhealth/configs/model/bert_base.json'

#********************************************************************************TRAIN********************************************************************************
# Num GPU
num_gpu: 2

# Distributed training
package: 'gloo'

# Device
device: 'cuda'

# Param
batch_size: 16
max_epoch: 100
early_stop: 10

# Optimizer
weight_decay: 0.02
init_lr: 0.0005
min_lr: 0.000001
warmup_lr: 0.000001
lr_decay_rate: 0.9
warmup_steps: 3000

#********************************************************************************MODEL********************************************************************************
# Model Name
bert_model: 'bert-base-uncased'