#********************************************************************************PATH********************************************************************************
# Output
output_dir: '../store_model/bert_corpus'

# Data
pretrain_path: '../data/corpus/ProcessedRedditRawData'

# Bert Config
bert_config: '../configs/model/bert_base.json'

# Checkpoint
train_checkpoint: '../store_model/bert_corpus/checkpoint_02.pth'

#********************************************************************************TRAIN********************************************************************************
# Num GPU
num_gpu: 4

# Distributed training
package: 'nccl'

# Device
device: 'cuda'

# Param
batch_size: 32
max_epoch: 100
early_stop: 5

# Optimizer
weight_decay: 0.02
init_lr: 0.00005
min_lr: 0.000001
warmup_lr: 0.000001
lr_decay_rate: 0.9
warmup_steps: 3000

#********************************************************************************MODEL********************************************************************************
# Model Name
bert_model: 'bert-base-uncased'