alpha: 0.9
alpha_center: 0.5
alpha_focal: 0.7
alpha_tverksy: 0.2
batch_size: 8
bert_config: ../configs/model/bert_base.json
bert_lr: 1.0e-05
bert_model: bert-base-uncased
bert_model_checkpoint: ../store_model/bert_corpus_checkpoint_30.pth
beta_tversky: 0.8
early_stop: 5
eval_device: cuda:1
gamma_focal: 2
loss:
- loss_focal
- loss_dice
- loss_tversky
- loss_contrast
- loss_reason
margin_contrast: 1.0
margin_lmcl: 0.35
max_epoch: 100
min_lr: 0
mlp_lr: 3.0e-05
num_gpu: 1
output_dir: ../paper_experiment/dreaddit/corpus_bert_best
package: gloo
prompt: ''
test_path: ../data/dreaddit/Processed/dreaddit_test_gpt4o_improved.csv
train_checkpoint: ''
train_device: cuda:1
train_path: ../data/dreaddit/Processed/dreaddit_train_gpt4o_improved.csv
val_path: ../data/dreaddit/Processed/dreaddit_val_gpt4o_improved.csv
weight_decay: 0.05
