#********************************************************************************PATH********************************************************************************
# Output
#output_dir: '../store_model/bert_lonely_train_focal'
#output_dir: '../store_model/bert_lonely_train'
#output_dir: '../store_model/bert_lonely_train_no_connect'
#output_dir: '../store_model/bert_lonely_train_fnn'
#output_dir: '../store_model/bert_lonely_train_dropout'
#output_dir: '../store_model/bert_lonely_train_center_angular'
#output_dir: '../store_model/bert_lonely_train_no_attn'
#output_dir: '../store_model/bert_lonely_train_center'
#output_dir: '../store_model/bert_lonely_train_first_last'
#output_dir: '../store_model/bert_lonely_train_connected_output'
#output_dir: '../store_model/bert_lonely_reddit'
#output_dir: '../store_model/bert_lonely_combine_all'
#output_dir: '../store_model/bert_lonely_mental_mlp'
#output_dir: '../store_model/bert_lonely_base_mlp'
#output_dir: '../store_model/bert_lonely_mental_focal'
#output_dir: '../store_model/bert_lonely_mental_mlp3'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.9'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment1'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.3alpha'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.2alpha'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.1alpha'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.25alpha'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.15alpha'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.2alpha0.8focal'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.2alpha0.6focal'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.2alpha1.25constrast'
#output_dir: '../store_model/bert_lonely_mental_mlp512lonelysentiment0.2alpha0.75constrast'
#output_dir: '../store_model/bert_lonely_mental_best2.1gamma'
#output_dir: '../store_model/bert_lonely_mental_best_3loss'
#output_dir: '../store_model/bert_lonely_mental_best_contrast'
#output_dir: '../store_model/bert_lonely_mental_best_embed'
#output_dir: '../store_model/bert_lonely_mental_best_gpt4o'
#output_dir: '../store_model/bert_lonely_mental_best_no_decoder'
#output_dir: '../store_model/bert_lonely_mental_best_question'
#output_dir: '../store_model/bert_lonely_mental_best_test'
#output_dir: '../store_model/bert_lonely_mental_best_bert_base'
#output_dir: '../store_model/bert_lonely_mental_best_anxiety_corpus'
#output_dir: '../store_model/bert_lonely_mental_best_dr'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_sent_1'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_sent_3'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_2'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_40'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_30'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_20'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_35'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_33'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_37'
#output_dir: '../store_model/bert_lonely_mental_best_bert_corpus_25'
output_dir: '../store_model/bert_lonely_mental_bert_test'

# Data
train_path: '../data/dreaddit/Processed/processed_dreaddit-train.csv'
val_path: '../data/dreaddit/Processed/processed_dreaddit-val.csv'
test_path: '../data/dreaddit/Processed/processed_dreaddit-test.csv'
#train_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-train-1.csv'
#val_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-val-1.csv'
#test_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-test-1.csv'
#train_path: '../data/dreaddit/Processed/dreaddit_train_gpt4o_improved.csv'
#val_path: '../data/dreaddit/Processed/dreaddit_val_gpt4o_improved.csv'
#test_path: '../data/dreaddit/Processed/dreaddit_test_gpt4o_improved.csv'
#train_path: '../data/combine/combine_train.csv'
#val_path: '../data/combine/combine_val.csv'
#test_path: '../data/combine/combine_test.csv'
#train_path: '../data/multiwd/process/train.csv'
#val_path: '../data/multiwd/process/val.csv'
#test_path: '../data/multiwd/process/test.csv'
#train_path: '../data/DR/process/train.csv'
#val_path: '../data/DR/process/val.csv'
#test_path: '../data/DR/process/test.csv'

# Checkpoint
train_checkpoint: ''
eval_checkpoint: '../store_model/bert_lonely_train/checkpoint_16.pth'

# Bert Config
bert_config: '../configs/model/bert_base.json'

#********************************************************************************TRAIN********************************************************************************
# Num GPU
num_gpu: 1

# Distributed training
package: 'gloo'

# Device
train_device: 'cuda:1'
eval_device: 'cuda:1'

# Param
batch_size: 8
max_epoch: 100
early_stop: 5

# Optimizer
bert_lr: 0.00001
mlp_lr: 0.00003
weight_decay: 0.05
min_lr: 0

# Prompt
prompt: ''

#********************************************************************************MODEL********************************************************************************
# Model Name
#bert_model: 'mental/mental-bert-base-uncased'
bert_model: 'bert-base-uncased'
bert_model_checkpoint: '../store_model/bert_corpus_checkpoint_30.pth'

# Loss
loss:
  - loss_focal
  - loss_dice
  - loss_tversky
  - loss_contrast
  - loss_reason

# Dropout rate
dropout_rate: 0.5

# Number of attention heads for classifier
num_head_classifier: 8

#********************************************************************************LOSS********************************************************************************
# Alpha for loss allocation
alpha: 0.9 # Ratio of lonely losses to sentiment losses (i.e., 0.75 * loss_focal_lonely + (1 - 0.75) * loss_focal_sentiment)

# Center Loss
alpha_center: 0.5

# Margin Loss
margin_lmcl: 0.35

# Focal Loss
alpha_focal: 0.7 # Higher value penalizes positive over negative more
gamma_focal: 2 # Higher value penalizes indifferent probabilities

# Tversky Loss
alpha_tverksy: 0.2 # Higher value penalizes False Negatives more (identifying a person as not lonely when they actually are)
beta_tversky: 0.8 # Higher value penalizes False Positives more (identifying a person as lonely when they actually are not)

# Constrastive Loss
margin_contrast: 1.0 # Distance between positive and negative embeddings