# Output
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_focal'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_no_connect'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_fnn'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_dropout'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_center_angular'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_no_attn'
output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_center'

# Data
train_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/processed_dreaddit-train.csv'
val_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/processed_dreaddit-val.csv'
test_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/processed_dreaddit-test.csv'

#train_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/loneliness/OurLabeledData/SamplingData-1/loneliness-train-1.csv'
#val_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/loneliness/OurLabeledData/SamplingData-1/loneliness-val-1.csv'
#test_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/loneliness/OurLabeledData/SamplingData-1/loneliness-test-1.csv'

# Device
#train_device: 'cuda:0'
#eval_device: 'cuda:1'
train_device: 'cuda:1'
eval_device: 'cuda:0'

# Dropout rate
dropout_rate: 0.5

# Alpha for loss allocation
alpha: 0.7 # Ratio of loss_lonely to loss_sentiment (i.e., 0.7 * loss_lonely + (1 - 0.7) * loss_sentiment)

# Center Loss
alpha_center: 0.5

# Margin Loss
margin_lmcl: 0.35

# Focal Loss
alpha_focal: 0.7 # Higher value penalizes positive over negative more
gamma_focal: 2 # Higher value penalizes indifferent probabilities

# Tversky Loss
alpha_tverksy: 0.3 # Higher value penalizes False Negatives (identifying a person as not lonely when they actually are)
beta_tversky: 0.7 # Higher value penalizes False Positives (identifying a person as lonely when they actually are not)

# Constrastive Loss
margin_constrast: 1.0 # Distance between positive and negative embeddings

# Number of attention heads for classifier
num_head_classifier: 8

# Train
batch_size: 8
max_epoch: 1000
early_stop: 10

# Pretrain BERT
pretrain_path: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_base_uncased.pth'
#pretrain_path: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_finetune/bert_lonely_finetune.pth'

# Eval checkpoint
eval_checkpoint: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train/checkpoint_16.pth'

# Checkpoint
checkpoint: None

# Prompt
prompt: ''

# Bert Config
bert_config: 'C:/Winston/MentalHealthResearch/mentalhealth/configs/model/bert_base.json'

# Optimizer
##Cosine
#init_lr: 0.01
#weight_decay: 0.05
#min_lr: 0

##Warmup
weight_decay: 0.02
init_lr: 0.0001
min_lr: 0.000001
warmup_lr: 0.000001
lr_decay_rate: 0.9
warmup_steps: 30
