#********************************************************************************PATH********************************************************************************
# Output
#******************************Dreaddit******************************
#********MLP Comparison********
#output_dir: '../paper_experiment/dreaddit/corpus_bert_mlp'
#output_dir: '../paper_experiment/dreaddit/mental_bert_mlp'
#output_dir: '../paper_experiment/dreaddit/base_bert_mlp'
#********Best Comparison********
#output_dir: '../paper_experiment/dreaddit/corpus_bert_best'
#output_dir: '../paper_experiment/dreaddit/base_bert_best'
#output_dir: '../paper_experiment/dreaddit/mental_bert_best'
#********Decoder Comparison********
#output_dir: '../paper_experiment/dreaddit/corpus_bert_no_decoder'
#output_dir: '../paper_experiment/dreaddit/corpus_bert_no_decoder_0.95'
#********Sentiment Comparison********
#output_dir: '../paper_experiment/dreaddit/corpus_bert_no_sentiment'
#********Sentence Comparison********
#output_dir: '../paper_experiment/dreaddit/corpus_bert_mlp_sentence'
#output_dir: '../paper_experiment/dreaddit/corpus_sentence_bert_mlp_sentence'
#output_dir: '../paper_experiment/dreaddit/mental_bert_mlp_sentence'
#********Last Layer Comparison********
#output_dir: '../paper_experiment/dreaddit/corpus_bert_mlp_no_last'
output_dir: '../paper_experiment/dreaddit/corpus_bert_mlp_all'
#********All Layer Comparison********
#output_dir: '../paper_experiment/dreaddit/corpus_bert_no_decoder_all'

#******************************SAD******************************
#********MLP Comparison********
#output_dir: '../paper_experiment/sad/corpus_bert_mlp'
#output_dir: '../paper_experiment/sad/mental_bert_mlp'
#output_dir: '../paper_experiment/sad/base_bert_mlp'
#********Best Comparison********
#output_dir: '../paper_experiment/sad/corpus_bert_best'
#output_dir: '../paper_experiment/sad/base_bert_best'
#output_dir: '../paper_experiment/sad/mental_bert_best'
#********Decoder Comparison********
#output_dir: '../paper_experiment/sad/corpus_bert_no_decoder'
#********Sentiment Comparison********
#output_dir: '../paper_experiment/sad/corpus_bert_no_sentiment'
#********Sentence Comparison********
#output_dir: '../paper_experiment/sad/corpus_bert_mlp_sentence'
#output_dir: '../paper_experiment/sad/corpus_sentence_bert_mlp_sentence'
#output_dir: '../paper_experiment/sad/mental_bert_mlp_sentence'
#********Last Layer Comparison********
#output_dir: '../paper_experiment/sad/corpus_bert_mlp_no_last'
#********All Layer Comparison********
#output_dir: '../paper_experiment/sad/corpus_bert_no_decoder_all'

#******************************LONELINESS******************************
#********MLP Comparison********
#output_dir: '../paper_experiment/loneliness/corpus_bert_mlp'
#output_dir: '../paper_experiment/loneliness/mental_bert_mlp'
#output_dir: '../paper_experiment/loneliness/base_bert_mlp'
#********Best Comparison********
#output_dir: '../paper_experiment/loneliness/corpus_bert_best'
#output_dir: '../paper_experiment/loneliness/base_bert_best'
#output_dir: '../paper_experiment/loneliness/mental_bert_best'
#********Decoder Comparison********
#output_dir: '../paper_experiment/loneliness/corpus_bert_no_decoder'
#output_dir: '../paper_experiment/loneliness/corpus_bert_no_decoder_0.8'
#output_dir: '../paper_experiment/loneliness/corpus_bert_no_decoder_0.1'
#********Sentiment Comparison********
#output_dir: '../paper_experiment/loneliness/corpus_bert_no_sentiment'
#********Sentence Comparison********
#output_dir: '../paper_experiment/loneliness/corpus_bert_mlp_sentence'
#output_dir: '../paper_experiment/loneliness/corpus_sentence_bert_mlp_sentence'
#output_dir: '../paper_experiment/loneliness/mental_bert_mlp_sentence'
#********Last Layer Comparison********
#output_dir: '../paper_experiment/loneliness/corpus_bert_mlp_no_last'
#********All Layer Comparison********
#output_dir: '../paper_experiment/loneliness/corpus_bert_no_decoder_all'

#******************************CAMS******************************
#********MLP Comparison********
#output_dir: '../paper_experiment/cams/corpus_bert_mlp'
#output_dir: '../paper_experiment/cams/mental_bert_mlp'
#output_dir: '../paper_experiment/cams/base_bert_mlp'
#********Best Comparison********
#output_dir: '../paper_experiment/cams/corpus_bert_best'
#output_dir: '../paper_experiment/cams/base_bert_best'
#output_dir: '../paper_experiment/cams/mental_bert_best'
#********Decoder Comparison********
#output_dir: '../paper_experiment/cams/corpus_bert_no_decoder'
#********Sentiment Comparison********
#output_dir: '../paper_experiment/cams/corpus_bert_no_sentiment'
#********Sentence Comparison********
#output_dir: '../paper_experiment/cams/corpus_bert_mlp_sentence'
#output_dir: '../paper_experiment/cams/corpus_sentence_bert_mlp_sentence'
#output_dir: '../paper_experiment/cams/mental_bert_mlp_sentence'
#********Last Layer Comparison********
#output_dir: '../paper_experiment/cams/corpus_bert_mlp_no_last'
#********All Layer Comparison********
#output_dir: '../paper_experiment/cams/corpus_bert_no_decoder_all'

# Data
#******************************Dreaddit******************************
#train_path: '../data/dreaddit/Processed/processed_dreaddit-train.csv'
#val_path: '../data/dreaddit/Processed/processed_dreaddit-val.csv'
#test_path: '../data/dreaddit/Processed/processed_dreaddit-test.csv'
train_path: '../data/dreaddit/Processed/dreaddit_train_gpt4o_improved.csv'
val_path: '../data/dreaddit/Processed/dreaddit_val_gpt4o_improved.csv'
test_path: '../data/dreaddit/Processed/dreaddit_test_gpt4o_improved.csv'

#******************************Lonely******************************
#train_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-train-1.csv'
#val_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-val-1.csv'
#test_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-test-1.csv'
#train_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-train-1_gpt4o_improved.csv'
#val_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-val-1_gpt4o_improved.csv'
#test_path: '../data/loneliness/OurLabeledData/SamplingData-1/loneliness-test-1_gpt4o_improved.csv'
#******************************SAD******************************
#train_path: '../data/SAD/process/train.csv'
#val_path: '../data/SAD/process/val.csv'
#test_path: '../data/SAD/process/test.csv'
#train_path: '../data/SAD/process/sad_train_gpt4o_improved.csv'
#val_path: '../data/SAD/process/sad_val_gpt4o_improved.csv'
#test_path: '../data/SAD/process/sad_test_gpt4o_improved.csv'

#******************************CAMS******************************
#train_path: '../data/CAMS/SamplingData-1/cams-train.csv'
#val_path: '../data/CAMS/SamplingData-1/cams-val.csv'
#test_path: '../data/CAMS/SamplingData-1/cams-test.csv'

# Checkpoint
train_checkpoint: ''

# Bert Config
bert_config: '../configs/model/bert_base.json'

#********************************************************************************TRAIN********************************************************************************
# Num GPU
num_gpu: 1

# Distributed training
package: 'gloo'

# Device
train_device: 'cuda:1'
eval_device: 'cuda:1'

# Param
batch_size: 8
max_epoch: 100
early_stop: 5

# Optimizer
bert_lr: 0.00001
mlp_lr: 0.00003
weight_decay: 0.05
min_lr: 0

# Prompt
prompt: ''

# Number of classes
num_class: 2
#num_class: 9
#num_class: 6

# Embedding type
embed_type: 'document'
#embed_type: 'sentence'

# BERT Layer Train
bert_layer_train: 'all'

#********************************************************************************MODEL********************************************************************************
# Model Name
#bert_model: 'mental/mental-bert-base-uncased'
bert_model: 'bert-base-uncased'
#bert_model_checkpoint: ''
bert_model_checkpoint: '../store_model/bert_corpus_checkpoint_30.pth'
#bert_model_checkpoint: '../store_model/bert_corpus_sent_checkpoint_03.pth'

# Loss
loss:
  - loss_ce
#  - loss_focal
#  - loss_dice
#  - loss_tversky
#  - loss_contrast
#  - loss_reason

#********************************************************************************LOSS********************************************************************************
# Alpha for loss allocation
#alpha: 0.9 # Ratio of lonely losses to sentiment losses (i.e., 0.75 * loss_focal_task + (1 - 0.75) * loss_focal_sentiment)
#alpha: 1.0
alpha: 0.95

# Center Loss
alpha_center: 0.5

# Margin Loss
margin_lmcl: 0.35

# Focal Loss
alpha_focal: 0.7 # Higher value penalizes positive over negative more
gamma_focal: 2 # Higher value penalizes indifferent probabilities

# Tversky Loss
alpha_tverksy: 0.2 # Higher value penalizes False Negatives more (identifying a person as not lonely when they actually are)
beta_tversky: 0.8 # Higher value penalizes False Positives more (identifying a person as lonely when they actually are not)

# Constrastive Loss
margin_contrast: 1.0 # Distance between positive and negative embeddings