#********************************************************************************PATH********************************************************************************
# Output
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_focal'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_no_connect'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_fnn'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_dropout'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_center_angular'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_no_attn'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_center'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_first_last'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train_connected_output'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_reddit'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_combine_all'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_mental_mlp'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_base_mlp'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_mental_focal'
#output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_mental_mlp3'
output_dir: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_mental_mlp64'

# Data
train_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/processed_dreaddit-train.csv'
val_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/processed_dreaddit-val.csv'
test_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/processed_dreaddit-test.csv'
#train_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/loneliness/OurLabeledData/SamplingData-1/loneliness-train-1.csv'
#val_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/loneliness/OurLabeledData/SamplingData-1/loneliness-val-1.csv'
#test_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/loneliness/OurLabeledData/SamplingData-1/loneliness-test-1.csv'
#train_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/dreaddit_train_gpt4o.csv'
#val_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/dreaddit_val_gpt4o.csv'
#test_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/dreaddit/Processed/dreaddit_test_gpt4o.csv'
#train_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/combine/combine_train.csv'
#val_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/combine/combine_val.csv'
#test_path: 'C:/Winston/MentalHealthResearch/mentalhealth/data/combine/combine_test.csv'

# Eval checkpoint
eval_checkpoint: 'C:/Winston/MentalHealthResearch/mentalhealth/store_model/bert_lonely_train/checkpoint_16.pth'

# Bert Config
bert_config: 'C:/Winston/MentalHealthResearch/mentalhealth/configs/model/bert_base.json'

#********************************************************************************TRAIN********************************************************************************
# Device
train_device: 'cuda:0'
eval_device: 'cuda:1'

# Param
batch_size: 8
max_epoch: 100
early_stop: 10

# Optimizer
bert_lr: 0.00001
mlp_lr: 0.00003
weight_decay: 0.05
min_lr: 0

# Prompt
prompt: ''

#********************************************************************************MODEL********************************************************************************
# Model Name
model_name: 'mental/mental-bert-base-uncased'
#model_name: 'bert-base-uncased'

# Dropout rate
dropout_rate: 0.5

# Number of attention heads for classifier
num_head_classifier: 8

#********************************************************************************LOSS********************************************************************************
# Alpha for loss allocation
alpha: 0.7 # Ratio of loss_lonely to loss_sentiment (i.e., 0.7 * loss_lonely + (1 - 0.7) * loss_sentiment)

# Center Loss
alpha_center: 0.5

# Margin Loss
margin_lmcl: 0.35

# Focal Loss
alpha_focal: 0.7 # Higher value penalizes positive over negative more
gamma_focal: 2 # Higher value penalizes indifferent probabilities

# Tversky Loss
alpha_tverksy: 0.3 # Higher value penalizes False Negatives (identifying a person as not lonely when they actually are)
beta_tversky: 0.7 # Higher value penalizes False Positives (identifying a person as lonely when they actually are not)

# Constrastive Loss
margin_constrast: 1.0 # Distance between positive and negative embeddings